"""create_team_game_batting_lines

Revision ID: 166b6424e4f9
Revises:
Create Date: 2026-08-05 08:28:01.704289

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "166b6424e4f9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_game_batting_lines",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_pk", sa.Integer(), nullable=False),
        sa.Column("game_date", sa.Date(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("team_name", sa.String(), nullable=False),
        sa.Column("opponent_id", sa.Integer(), nullable=False),
        sa.Column("opponent_name", sa.String(), nullable=False),
        sa.Column("home_away", sa.String(), nullable=False),
        sa.Column("hits", sa.Integer(), nullable=False),
        sa.Column("runs", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("game_number", sa.Integer(), nullable=False),
        sa.Column("doubleheader", sa.Boolean(), nullable=False),
        sa.Column("scheduled_innings", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "home_away IN ('home', 'away')",
            name=op.f("ck_team_game_batting_lines_home_away_valid"),
        ),
        sa.CheckConstraint(
            "game_number >= 1", name=op.f("ck_team_game_batting_lines_game_number_min")
        ),
        sa.CheckConstraint(
            "game_pk > 0", name=op.f("ck_team_game_batting_lines_game_pk_positive")
        ),
        sa.CheckConstraint(
            "hits >= 0", name=op.f("ck_team_game_batting_lines_hits_nonnegative")
        ),
        sa.CheckConstraint(
            "opponent_id > 0",
            name=op.f("ck_team_game_batting_lines_opponent_id_positive"),
        ),
        sa.CheckConstraint(
            "runs >= 0", name=op.f("ck_team_game_batting_lines_runs_nonnegative")
        ),
        sa.CheckConstraint(
            "scheduled_innings >= 1",
            name=op.f("ck_team_game_batting_lines_scheduled_innings_min"),
        ),
        sa.CheckConstraint(
            "season > 0", name=op.f("ck_team_game_batting_lines_season_positive")
        ),
        sa.CheckConstraint(
            "team_id > 0", name=op.f("ck_team_game_batting_lines_team_id_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_game_batting_lines")),
        sa.UniqueConstraint(
            "team_id", "game_pk", name="uq_team_game_batting_lines_team_id_game_pk"
        ),
    )
    op.create_index(
        "ix_team_game_batting_lines_team_season_order",
        "team_game_batting_lines",
        ["team_id", "season", "game_date", "game_number", "game_pk"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_team_game_batting_lines_team_season_order",
        table_name="team_game_batting_lines",
    )
    op.drop_table("team_game_batting_lines")
    # ### end Alembic commands ###
